"""empty message

Revision ID: 1bc489befb61
Revises: 922267de8216
Create Date: 2021-12-27 17:58:26.414496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc489befb61'
down_revision = '922267de8216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('option_1', sa.Text(), nullable=False),
    sa.Column('option_2', sa.Text(), nullable=False),
    sa.Column('mbti_indicator', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
