"""empty message

Revision ID: 922267de8216
Revises: 
Create Date: 2021-12-27 15:52:18.446534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922267de8216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soulmate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_mbti', sa.String(length=10), nullable=False),
    sa.Column('soulmate_mbti', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('mbti', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('ans1', sa.Boolean(), nullable=True),
    sa.Column('ans2', sa.Boolean(), nullable=True),
    sa.Column('ans3', sa.Boolean(), nullable=True),
    sa.Column('ans4', sa.Boolean(), nullable=True),
    sa.Column('ans5', sa.Boolean(), nullable=True),
    sa.Column('ans6', sa.Boolean(), nullable=True),
    sa.Column('ans7', sa.Boolean(), nullable=True),
    sa.Column('ans8', sa.Boolean(), nullable=True),
    sa.Column('ans9', sa.Boolean(), nullable=True),
    sa.Column('ans10', sa.Boolean(), nullable=True),
    sa.Column('ans11', sa.Boolean(), nullable=True),
    sa.Column('ans12', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satisfaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satisfaction')
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('soulmate')
    op.drop_table('movie')
    # ### end Alembic commands ###
